function [pred,newData] = rulePrd(myData)
    fieldNames = fields(myData);
    [~,~,wheresNan] = removeNansAnd3FromData(myData);
    maskVect = ones([length(myData.(fieldNames{1})),1]);
    maskVect(wheresNan) = 0; %Mask to predict as bad the cells with nan in some of their features (this may not be ideal).
    pred = myData.sScore < .2 ...
        & myData.centroidDist < .9 ...
        & myData.globalSNR < 100 ...
        & myData.RMS < 10 ...
        & myData.interCorr >.1 ...
        & myData.peakSNR < 10 ...
        & myData.imMovCorr > 0 ...
        & myData.CellArea > 100 ...
        & myData.CellEccentricity < .9 ...
        & myData.CellSolidity > .8 ...
        & myData.EventArea > 10 ...
        & myData.EventEccentricity < 1 ...
        & myData.EventSolidity > .8 ...
        & myData.imMovCorr > .25;
    
        for k = 1:length(fieldNames)
            newData.(fieldNames{k}) = myData.(fieldNames{k})(pred);
        end

end

