function [y] = NCcostFn(x,d1,d2,allCellMapsMax)      
    options = NoRMCorreSetParms('d1',d1,'d2',d2,...
        'bin_width',1,...
        'use_parallel',1,...
        'correct_bidir',0,...
        'upd_template',0,...
        'shifts_method','linear',...
        'grid_size',[round(d1/x(1)),round(d2/x(1)),1],...
        'min_patch_size',[x(2),x(2),1],...
        'max_shift',x(3),...
        'iter',x(4),...
        'us_fac',x(5),...
        'mot_uf',x(6));
    
        MprFullNC = cell([1,length(allCellMapsMax)]);
        templateIdx = round(length(allCellMapsMax)./2);
        for j = 1:length(allCellMapsMax)
            MprFullNC{j} = normcorre(allCellMapsMax{j},options,allCellMapsMax{templateIdx});
        end
        
        corrMatNC = zeros([1,length(allCellMapsMax)]);
        for j = 1:length(allCellMapsMax)
            corrMatNC(j) = corr2(allCellMapsMax{templateIdx},MprFullNC{j});
        end
        y = -mean(abs(corrMatNC(setdiff(1:length(allCellMapsMax),templateIdx))));
end

